app/lib/noodl_web/router.ex
defmodule NoodlWeb.Router do
  use NoodlWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {NoodlWeb.LayoutView, :root}
    plug NoodlWeb.Plug.UserAgent
    plug NoodlWeb.Plug.Authentication
    plug NavigationHistory.Tracker, excluded_paths: ["/login", "/sign-up"], history_size: 3
  end

  pipeline :browser_hook do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  pipeline :logged_in do
    plug NoodlWeb.Plug.ValidateUser
  end

  pipeline :event_manager do
    plug NoodlWeb.Plug.ValidateEventManager
  end

  pipeline :capacity_check do
    plug NoodlWeb.Plug.ValidateSpectator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :stripe do
    plug :accepts, ["json"]
    plug NoodlWeb.Plug.StripeValidator
  end

  scope "/", NoodlWeb do
    pipe_through :browser

    live "/", Live.Pages.Index

    # User routes
    live "/sign-up", Live.Accounts.SignUp, :sign_up
    post "/sign-up", AccountsController, :sign_up

    live "/login", Live.Accounts.Login, :login
    post "/login", AccountsController, :login

    get "/logout", AccountsController, :logout
    get "/unsubscribe", AccountsController, :unsubscribe

    get "/oauth/connect", AccountsController, :connect
    get "/:provider/oauth/callback", AccountsController, :oauth

    # Legal stuff
    live "/terms-and-conditions", Live.Pages.TermsAndConditions
    live "/privacy-policy", Live.Pages.PrivacyPolicy
  end

  scope "/guide", NoodlWeb do
    pipe_through :browser

    live "/", Live.Guide.Index
    live "/stream", Live.Guide.Stream
  end

  scope "/account", NoodlWeb do
    pipe_through :browser

    get "/confirmation", AccountsController, :confirmation

    live "/password-reset", Live.Accounts.PasswordReset
    live "/forgot-password", Live.Accounts.ForgotPassword
  end

  scope "/profile", NoodlWeb.Live.Accounts do
    pipe_through [:browser, :logged_in]

    live "/", Profile
    live "/security", Security
    live "/events", Events
    live "/notifications", Notifications
    live "/communications", Communication
  end

  scope "/ticket", NoodlWeb do
    pipe_through [:browser, :logged_in]

    live "/checkout", Live.Ticketing.Release.Checkout
    post "/checkout", ReleaseController, :checkout

    get "/checkout/completed", ReleaseController, :completed
  end

  scope "/events", NoodlWeb do
    pipe_through [:browser, :logged_in]

    live "/:id/proposals/new", Live.Events.Proposal.New

    live "/new", Live.Events.New, :new
    post "/new", EventsController, :payment
  end

  scope "/events", NoodlWeb do
    pipe_through [:browser, :capacity_check]

    live "/:event/sessions/:session",
         Live.Events.Session.Dashboard,
         :dashboard
  end

  scope "/events", NoodlWeb do
    pipe_through :browser

    live "/", Live.Events.Index, :index
    live "/:id", Live.Events.Show, :show
    live "/:id/recordings", Live.Events.Recordings
    live "/:id/members", Live.Events.Members

    get "/:id/calendar", EventsController, :calendar
    get "/:id/calendar/:session", EventsController, :calendar
  end

  scope "/events", NoodlWeb do
    pipe_through [:browser, :logged_in, :event_manager]

    live "/:id/manage", Live.Events.Manage
    live "/:id/manage/:view", Live.Events.Manage
    get "/:id/recording/:recording_id/download", EventsController, :download_recording
  end

  # Other scopes may use custom stacks.
  scope "/stripe", NoodlWeb do
    pipe_through :stripe

    post "/webhook", WebhookController, :stripe
  end

  scope "/", NoodlWeb do
    pipe_through :browser_hook
    post "/:provider/oauth/callback", AccountsController, :oauth
  end

  scope "/agora", NoodlWeb do
    pipe_through :api

    post "/webhook", WebhookController, :agora
    get "/webhook", WebhookController, :agora
  end

  if Mix.env() == :dev do
    scope "/livestream", NoodlWeb do
      post "/play", WebhookController, :livestream
      post "/publish", WebhookController, :livestream
      post "/done", WebhookController, :livestream
      post "/recording-done", WebhookController, :livestream
    end
  end

  scope "/" do
    # local email previews
    if Mix.env() == :dev || System.get_env("SMTP_PASSWORD") == nil do
      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end
end

app/lib/noodl/accounts/feedback.ex
defmodule Noodl.Accounts.Feedback do
  use Ecto.Schema
  import Ecto.Changeset

  alias Noodl.Accounts.User

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "feedback" do
    field :description, :string
    field :subject, :string
    field :type, :string
    belongs_to :user, User

    timestamps()
  end

  @doc false
  def changeset(feedback, attrs) do
    feedback
    |> cast(attrs, [:subject, :type, :description])
    |> validate_required([:subject, :type, :description])
  end
end

app/lib/noodl/accounts/push_subscription.ex
defmodule Noodl.Accounts.PushSubscription do
  use Ecto.Schema
  import Ecto.Changeset

  alias Noodl.Accounts.User

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "push_subscriptions" do
    field :endpoint, :string
    field :private_key, :string
    field :public_key, :string

    belongs_to :user, User

    timestamps()
  end

  @doc false
  def changeset(push_subscription, attrs) do
    push_subscription
    |> cast(attrs, [:endpoint, :private_key, :public_key, :user_id])
    |> validate_required([:endpoint, :private_key, :public_key, :user_id])
    |> unique_constraint([:endpoint, :private_key, :public_key])
  end
end

app/lib/noodl/accounts/role.ex
defmodule Noodl.Accounts.Role do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "roles" do
    field :name, :string
    field :description, :string

    timestamps()
  end

  @doc false
  def changeset(role, attrs) do
    role
    |> cast(attrs, [:name, :description])
    |> validate_required([:name, :description])
  end
end

app/lib/noodl/accounts/subscription.ex
defmodule Noodl.Accounts.Subscription do
  use Ecto.Schema
  import Ecto.Changeset

  alias Noodl.Accounts.User

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "subscriptions" do
    field :email, :string
    field :type, :string
    field :unsubscribed, :boolean, default: false

    belongs_to :user, User

    timestamps()
  end

  @doc false
  def changeset(subscription, attrs) do
    subscription
    |> cast(attrs, [:type, :email, :unsubscribed, :user_id])
    |> validate_required([:type, :email, :unsubscribed])
    |> unique_constraint([:email, :type])
  end
end

app/lib/noodl/accounts/user.ex
defmodule Noodl.Accounts.User do
  @moduledoc """
  User Schema
  """

  use Ecto.Schema
  use Waffle.Ecto.Schema
  import Ecto.Changeset

  alias Noodl.Accounts.{PushSubscription, Subscription, UserRole}
  alias Noodl.Ticketing.Ticket
  alias Noodl.Uploaders.ProfilePhoto

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "users" do
    field :email, :string
    field :firstname, :string
    field :lastname, :string
    field :password_hash, :string
    field :stripe_account, :string
    field :confirmed, :boolean, default: false
    field :display_name, :string
    field :recording_id, :integer
    field :social_link, :string
    field :social_username, :string

    field :profile_photo, ProfilePhoto.Type

    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    has_many :tickets, Ticket
    has_many :push_subscription, PushSubscription
    has_many :subscriptions, Subscription
    has_many :user_roles, UserRole

    timestamps()
  end

  def changeset(user, attrs) do
    user
    |> cast(attrs, [
      :firstname,
      :lastname,
      :email,
      :password,
      :password_confirmation,
      :stripe_account,
      :confirmed,
      :recording_id,
      :social_link,
      :social_username
    ])
    |> validate_required([:firstname, :lastname, :email],
      message: "Missing required fields"
    )
    |> validate_length(:email,
      min: 6,
      max: 256,
      message: "Email must be between 6 and 256 characters"
    )
    |> validate_length(:display_name, max: 64)
    |> unique_constraint(:email, message: "Email is invalid")
  end

  def signup_changeset(user, attrs) do
    user
    |> cast(attrs, [:firstname, :lastname, :email, :password, :password_confirmation])
    |> validate_required([:email, :password, :password_confirmation],
      message: "Missing required fields"
    )
    |> validate_length(:email,
      min: 6,
      max: 256,
      message: "Email must be between 6 and 256 characters"
    )
    |> validate_length(:password,
      min: 6,
      max: 64,
      message: "Password must be between 6 and 64 characters"
    )
    |> validate_length(:display_name, max: 64)
    |> unique_constraint(:email, message: "Email is invalid")
    |> validate_confirmation(:password, message: "Passwords do not match")
  end

  def oauth_changeset(user, attrs) do
    user
    |> cast(attrs, [:firstname, :lastname, :email, :confirmed])
    |> validate_required([:email],
      message: "Missing required fields"
    )
    |> validate_length(:email,
      min: 6,
      max: 256,
      message: "Email must be between 6 and 256 characters"
    )
    |> validate_length(:display_name, max: 64)
    |> unique_constraint(:email, message: "Email is invalid")
  end

  def login_changeset(user, attrs) do
    user
    |> cast(attrs, [:email, :password])
    |> validate_required([:email, :password])
  end

  def forgot_password_changeset(user, attrs) do
    user
    |> cast(attrs, [:email])
    |> validate_required([:email])
  end

  def update_changeset(user, attrs) do
    user
    |> cast(attrs, [
      :firstname,
      :lastname,
      :email,
      :confirmed,
      :display_name,
      :social_link,
      :social_username
    ])
    |> validate_required([:email],
      message: "Missing required fields"
    )
    |> validate_length(:display_name, max: 64)
  end

  def password_reset_changeset(user, attrs) do
    user
    |> cast(attrs, [:password, :password_confirmation])
    |> validate_required([:password, :password_confirmation],
      message: "Missing required fields"
    )
    |> validate_length(:password,
      min: 6,
      max: 64,
      message: "Password must be between 6 and 64 characters"
    )
    |> validate_confirmation(:password, message: "Passwords do not match")
  end

  def add_password(%{changes: %{password: password}} = user) do
    password_hash = Argon2.hash_pwd_salt(password)

    user
    |> put_change(:password_hash, password_hash)
  end

  def add_password(changeset), do: changeset

  def validate_password(changeset, field, _options \\ []) do
    validate_change(changeset, field, fn _, password ->
      {:data, password_hash} = fetch_field(changeset, :password_hash)

      case Argon2.verify_pass(password, password_hash) do
        true ->
          []

        false ->
          [{field, "Invalid email or password"}]
      end
    end)
  end
end

app/lib/noodl_web/controllers/accounts_controller.ex
defmodule NoodlWeb.AccountsController do
  use NoodlWeb, :controller

  alias Phoenix.LiveView.Controller
  alias Noodl.Accounts
  alias Noodl.Accounts.User
  alias Noodl.MultiProvider
  alias NoodlWeb.Endpoint
  alias NoodlWeb.Live.Accounts, as: LiveAccounts

  @max_age 86_400

  def sign_up(conn, %{"user" => %{"agree_terms" => "false"} = user}) do
    conn
    |> put_layout("bare.html")
    |> put_flash(:info, "Must accept terms to sign up.")
    |> Controller.live_render(LiveAccounts.SignUp,
      session: %{
        "changeset" => Accounts.User.signup_changeset(%User{}, user)
      }
    )
  end

  def sign_up(conn, %{"user" => user}) do
    with {:ok, %{user: user}} <- Accounts.create_user(user) do
      conn
      |> put_flash(:info, "Account created, check your email for confirmation.")
      |> put_session(:user, user.id)
      |> redirect(to: Routes.live_path(conn, LiveAccounts.Profile))
    else
      {:error, :user, %Ecto.Changeset{} = changeset, _} ->
        conn
        |> put_flash(:error, "Invalid user")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.SignUp,
          session: %{
            "changeset" => changeset
          }
        )

      e ->
        IO.inspect(e)

        conn
        |> put_flash(:error, "Unknown Error")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.SignUp,
          session: %{
            "changeset" => Accounts.User.signup_changeset(%User{}, %{})
          }
        )
    end
  end

  def login(conn, %{"user" => user}) do
    case Accounts.login_user(user) do
      {:ok, %{confirmed: true} = user} ->
        conn
        |> put_session(:user, user.id)
        # Doing this lets us disconnect a user globally. Like if we need to permaban
        # https://hexdocs.pm/phoenix_live_view/security-model.html#disconnecting-all-instances-of-a-given-live-user
        |> put_session(:live_socket_id, "users_socket:#{user.id}")
        |> redirect(
          to: NavigationHistory.last_path(conn) || Routes.live_path(conn, Live.Pages.Index)
        )

      {:ok, user} ->
        conn
        |> put_flash(:error, "You must confirm your account before you can sign in.")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.Login,
          session: %{
            "changeset" => Accounts.User.login_changeset(user, %{}),
            "user" => user
          }
        )

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Invalid login information")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.Login,
          session: %{
            "changeset" => changeset,
            "user" => user
          }
        )
    end
  end

  def logout(conn, _params) do
    conn
    |> clear_session()
    |> delete_resp_cookie("ack")
    |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
  end

  def connect(%{assigns: %{user: user}} = conn, %{"state" => state, "code" => account}) do
    # validate the incoming phoenix token
    # make sure its id is the same as the logged in person
    # update their account with the stripe account id
    with {:ok, user_id} <-
           Phoenix.Token.verify(Endpoint, "noodl stripe salt", state, max_age: @max_age),
         true <- user_id == user.id,
         {:ok, token} <- Stripe.Connect.OAuth.token(account),
         {:ok, user} <- Accounts.update_user(user, %{"stripe_account" => token.stripe_user_id}) do
      conn
      |> put_flash(:info, "Account connected.")
      |> put_session(:user, user.id)
      |> redirect(to: Routes.live_path(conn, Live.Accounts.Profile))
    else
      _ -> conn |> resp(403, "Unauthorized")
    end
  end

  def connect(conn, _params) do
    conn
    |> put_flash(:info, "Error occurred while connecting account.")
    |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
  end

  def confirmation(conn, %{"token" => token}) do
    with {:ok, user_id} <-
           Phoenix.Token.verify(Endpoint, "noodl confirmation", token, max_age: @max_age * 7),
         {:ok, user} <- Accounts.get_user(user_id),
         {:ok, user} <- Accounts.update_user(user, %{"confirmed" => true}) do
      conn
      |> put_flash(:info, "Account confirmed!")
      |> put_session(:user, user.id)
      |> redirect(to: Routes.live_path(conn, Live.Accounts.Profile))
    else
      _ -> conn |> resp(403, "Unauthorized")
    end
  end

  def unsubscribe(conn, %{"token" => token}) do
    with {:ok, %{email: email, type: type}} <-
           Phoenix.Token.verify(Endpoint, "noodl unsubscribe", token),
         {:ok, _sub} <-
           Accounts.create_subscription(%{
             "email" => email,
             "type" => type,
             "unsubscribed" => true
           }) do
      conn
      |> put_flash(:info, "You are now unsubscribed!")
      |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
    else
      {:error,
       %{
         errors: [
           email:
             {"has already been taken",
              [constraint: :unique, constraint_name: "subscriptions_email_type_index"]}
         ]
       }} ->
        conn
        |> put_flash(:info, "You have already unsubscribed.")
        |> redirect(to: Routes.live_path(conn, Live.Pages.Index))

      _ ->
        conn
        |> put_flash(:error, "An error occurred while unsubscribing. Please contact support.")
        |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
    end
  end

  def oauth(conn, %{"provider" => provider} = params)
      when provider in ["github", "apple", "google"] do
    params = Map.delete(params, "provider")

    {:ok, %{user: %{"email" => email}}} = MultiProvider.callback(String.to_atom(provider), params)

    case Accounts.get_user_by(email: email) do
      {:ok, user} ->
        conn
        |> put_session(:user, user.id)
        |> put_session(:live_socket_id, "users_socket:#{user.id}")
        |> put_resp_cookie("ack", %{user_id: user.id}, sign: true)
        |> redirect(to: Routes.live_path(conn, LiveAccounts.Profile))

      {:error, :not_found} ->
        {:ok, %{user: user}} =
          Accounts.create_oauth_user(%{"email" => email, "confirmed" => true})

        conn
        |> put_session(:user, user.id)
        |> put_session(:live_socket_id, "users_socket:#{user.id}")
        |> redirect(to: Routes.live_path(conn, LiveAccounts.Profile))
    end
  end
end

app/lib/noodl_web/live/accounts/events/events.html.leex
<div class="min-h-screen pt-16 pb-12 bg-gray-100">
  <div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8 lg:flex md:justify-between">
    <%= Phoenix.View.render NoodlWeb.AccountsView, "sidebar.html", Map.put(assigns, :view, "events") %>

    <div class="flex-1 mt-8 md:mt-0">
      <header>
        <h1 class="text-lg font-medium leading-6 text-gray-900">
          Events
        </h1>
      </header>

      <%= if not Enum.empty?(@current_created_events) do %>
      <div class="mt-8 md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
          <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
            Created
          </h2>
        </div>
        <div class="flex mt-4 md:mt-0 md:ml-4">
          <span class="ml-3 rounded-md shadow-sm">
            <%= live_redirect "Organize", to: Routes.events_new_path(@socket, :new), class: UI.button(:primary, :sm) %>
          </span>
        </div>
      </div>
      <div class="mt-4 overflow-hidden bg-white rounded-md shadow">
        <ul>
          <%= for event <- @current_created_events do %>
            <li class="border-t border-gray-200 first:border-t-0">
              <%= live_redirect class: "block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out", to: Routes.live_path(@socket, Live.Events.Manage, event.slug) do %>
                <div class="flex items-center px-4 py-4 sm:px-6">
                  <div class="flex items-center flex-1 min-w-0">
                    <div class="flex items-center flex-1 flex-shrink-0">
                      <img class="object-contain w-12 h-12 text-xs rounded-full"
                           src="<%= cover_photo_url(event) %>"
                           alt="<%= event.name %>"
                      />
                      <div class="flex items-center ml-4">
                        <div>
                          <div class="flex mx-2 items-center font-medium text-red-500">
                            <span class="mr-2"><%= event.name %></span>

                            <%= case event.is_live do %>
                              <% true -> %>
                                <span class="px-2 py-1 text-xs text-white uppercase bg-red-500 rounded">
                                  Published
                                </span>

                              <% false -> %>
                                <span class="px-2 py-1 text-xs text-white uppercase bg-yellow-500 rounded">
                                  Drafted
                                </span>
                            <% end %>
                          </div>

                          <div class="mx-2 flex items-center text-sm text-gray-500">
                            <span class="truncate">
                              <%= event.topic %>
                            </span>
                          </div>

                          <div class="flex flex-wrap mt-2">
                            <%= for %{role: role} <- event.user_roles do %>
                              <span class="mx-2 my-1 inline-flex items-center px-2.5 py-0.5 rounded-md text-sm font-medium leading-5 bg-red-100 text-red-800">
                                <%= role.name %>
                              </span>
                            <% end %>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div class="flex-1 min-w-0 px-4 md:grid md:grid-cols-1 md:gap-2">
                      <div class="hidden md:block">
                        <div>
                          <div class="text-sm leading-5 text-gray-900">
                            <span class="block text-xs font-medium tracking-wide text-gray-500 uppercase">Start</span>
                            <%= format_event_start_time(event, user_timezone(@socket)) %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <svg class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
                    </svg>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <% end%>

      <div class="mt-8 md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
          <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
            Attending
          </h2>
        </div>
        <div class="flex mt-4 md:mt-0 md:ml-4">
          <span class="ml-3 rounded-md shadow-sm">
            <%= live_redirect "Create an event", to: Routes.events_new_path(@socket, :new), class: UI.button(:primary, :sm) %>
          </span>
        </div>
      </div>
      <div class="mt-4 overflow-hidden bg-white rounded-md shadow">
        <%= if not Enum.empty?(@event_tickets) do %>
        <ul>
          <%= for event_ticket <- @event_tickets do %>
            <li class="border-t border-gray-200 first:border-t-0">
              <%= live_redirect class: "block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out", to: Routes.events_show_path(@socket, :show, event_ticket.event.slug) do %>
                <div class="flex items-center px-4 py-4 sm:px-6">
                  <div class="flex items-center flex-1 min-w-0">
                    <div class="flex-shrink-0">
                      <img class="object-contain w-12 h-12 text-xs rounded-full" src="<%= cover_photo_url(event_ticket.event) %>" alt="<%= event_ticket.event.name %>" />
                    </div>
                    <div class="flex-1 min-w-0 px-4 md:grid md:grid-cols-2 md:gap-4">
                      <div>
                        <div class="text-sm font-medium leading-5 text-red-600 truncate"><%= event_ticket.event.name %></div>
                        <div class="flex items-center text-sm leading-5 text-gray-500">
                          <span class="truncate"><%= event_ticket.event.topic %></span>
                        </div>

                        <%= for %{role: role} <- event_ticket.event.user_roles do %>
                          <span class="mx-2 my-1 inline-flex items-center px-2.5 py-0.5 rounded-md text-sm font-medium leading-5 bg-red-100 text-red-800">
                            <%= role.name %>
                          </span>
                        <% end %>
                      </div>
                      <div class="hidden md:block">
                        <div>
                          <div class="text-sm leading-5 text-gray-900">
                            <span class="block text-xs font-medium tracking-wide text-gray-500 uppercase">Start</span>
                            <%= format_time(event_ticket.event.start_datetime, "%B %e -") %>
                            <%= format_time(event_ticket.event.end_datetime, "%B %e") %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <svg class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
                    </svg>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
        <% else %>
        <div class="flex items-center justify-center">
          <div class="px-4 py-4 text-center sm:px-6">
            <span class="block mt-1 text-sm text-gray-600">You are not attending any events...</span>
            <span class="inline-flex mt-3 rounded-md shadow-sm">
              <%= live_redirect "Explore", to: Routes.events_index_path(@socket, :index), class: UI.button(:primary, :sm) %>
            </span>
          </div>
        </div>
        <% end%>
      </div>

      <%= if not Enum.empty?(@expired_created_events) do %>
      <div class="mt-8 md:flex md:items-center md:justify-between">
        <div class="flex-1 min-w-0">
          <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
            Previously Created
          </h2>
        </div>
      </div>
      <div class="mt-4 overflow-hidden bg-white rounded-md shadow">
        <ul>
          <%= for event <- @expired_created_events do %>
            <li class="border-t border-gray-200 first:border-t-0">
              <%= live_redirect class: "block hover:bg-gray-50 focus:outline-none focus:bg-gray-50 transition duration-150 ease-in-out", to: Routes.live_path(@socket, Live.Events.Manage, event.slug, :overview) do %>
                <div class="flex items-center px-4 py-4 sm:px-6">
                  <div class="flex items-center flex-1 min-w-0">
                    <div class="flex-shrink-0">
                      <img class="object-contain w-12 h-12 text-xs rounded-full" src="<%= cover_photo_url(event) %>" alt="<%= event.name %>" />
                    </div>
                    <div class="flex-1 min-w-0 px-4 md:grid md:grid-cols-2 md:gap-4">
                      <div>
                        <div class="text-sm font-medium leading-5 text-red-500 truncate"><%= event.name %></div>
                        <div class="flex items-center text-sm leading-5 text-gray-500">
                          <span class="truncate"><%= event.topic %></span>
                        </div>
                      </div>
                      <div class="hidden md:block">
                        <div>
                          <div class="text-sm leading-5 text-gray-900">
                            <span class="block text-xs font-medium tracking-wide text-gray-500 uppercase">Ended</span>
                            <%= format_event_start_time(event, user_timezone(@socket)) %>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <svg class="w-5 h-5 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                      <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd"/>
                    </svg>
                  </div>
                </div>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
      <% end %>
    </div>
  </div>
</section>