app/lib/noodl_web/router.ex
defmodule NoodlWeb.Router do
  use NoodlWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {NoodlWeb.LayoutView, :root}
    plug NoodlWeb.Plug.UserAgent
    plug NoodlWeb.Plug.Authentication
    plug NavigationHistory.Tracker, excluded_paths: ["/login", "/sign-up"], history_size: 3
  end

  pipeline :browser_hook do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :put_secure_browser_headers
  end

  pipeline :logged_in do
    plug NoodlWeb.Plug.ValidateUser
  end

  pipeline :event_manager do
    plug NoodlWeb.Plug.ValidateEventManager
  end

  pipeline :capacity_check do
    plug NoodlWeb.Plug.ValidateSpectator
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :stripe do
    plug :accepts, ["json"]
    plug NoodlWeb.Plug.StripeValidator
  end

  scope "/", NoodlWeb do
    pipe_through :browser

    live "/", Live.Pages.Index

    # User routes
    live "/sign-up", Live.Accounts.SignUp, :sign_up
    post "/sign-up", AccountsController, :sign_up

    live "/login", Live.Accounts.Login, :login
    post "/login", AccountsController, :login

    get "/logout", AccountsController, :logout
    get "/unsubscribe", AccountsController, :unsubscribe

    get "/oauth/connect", AccountsController, :connect
    get "/:provider/oauth/callback", AccountsController, :oauth

    # Legal stuff
    live "/terms-and-conditions", Live.Pages.TermsAndConditions
    live "/privacy-policy", Live.Pages.PrivacyPolicy
  end

  scope "/guide", NoodlWeb do
    pipe_through :browser

    live "/", Live.Guide.Index
    live "/stream", Live.Guide.Stream
  end

  scope "/account", NoodlWeb do
    pipe_through :browser

    get "/confirmation", AccountsController, :confirmation

    live "/password-reset", Live.Accounts.PasswordReset
    live "/forgot-password", Live.Accounts.ForgotPassword
  end

  scope "/profile", NoodlWeb.Live.Accounts do
    pipe_through [:browser, :logged_in]

    live "/", Profile
    live "/security", Security
    live "/events", Events
    live "/notifications", Notifications
    live "/communications", Communication
  end

  scope "/ticket", NoodlWeb do
    pipe_through [:browser, :logged_in]

    live "/checkout", Live.Ticketing.Release.Checkout
    post "/checkout", ReleaseController, :checkout

    get "/checkout/completed", ReleaseController, :completed
  end

  scope "/events", NoodlWeb do
    pipe_through [:browser, :logged_in]

    live "/:id/proposals/new", Live.Events.Proposal.New

    live "/new", Live.Events.New, :new
    post "/new", EventsController, :payment
  end

  scope "/events", NoodlWeb do
    pipe_through [:browser, :capacity_check]

    live "/:event/sessions/:session",
         Live.Events.Session.Dashboard,
         :dashboard
  end

  scope "/events", NoodlWeb do
    pipe_through :browser

    live "/", Live.Events.Index, :index
    live "/:id", Live.Events.Show, :show
    live "/:id/recordings", Live.Events.Recordings
    live "/:id/members", Live.Events.Members

    get "/:id/calendar", EventsController, :calendar
    get "/:id/calendar/:session", EventsController, :calendar
  end

  scope "/events", NoodlWeb do
    pipe_through [:browser, :logged_in, :event_manager]

    live "/:id/manage", Live.Events.Manage
    live "/:id/manage/:view", Live.Events.Manage
    get "/:id/recording/:recording_id/download", EventsController, :download_recording
  end

  # Other scopes may use custom stacks.
  scope "/stripe", NoodlWeb do
    pipe_through :stripe

    post "/webhook", WebhookController, :stripe
  end

  scope "/", NoodlWeb do
    pipe_through :browser_hook
    post "/:provider/oauth/callback", AccountsController, :oauth
  end

  scope "/agora", NoodlWeb do
    pipe_through :api

    post "/webhook", WebhookController, :agora
    get "/webhook", WebhookController, :agora
  end

  if Mix.env() == :dev do
    scope "/livestream", NoodlWeb do
      post "/play", WebhookController, :livestream
      post "/publish", WebhookController, :livestream
      post "/done", WebhookController, :livestream
      post "/recording-done", WebhookController, :livestream
    end
  end

  scope "/" do
    # local email previews
    if Mix.env() == :dev || System.get_env("SMTP_PASSWORD") == nil do
      forward "/sent_emails", Bamboo.SentEmailViewerPlug
    end
  end
end

app/lib/noodl/accounts/role.ex
defmodule Noodl.Accounts.Role do
  use Ecto.Schema
  import Ecto.Changeset

  @primary_key {:id, :binary_id, autogenerate: true}
  @foreign_key_type :binary_id
  schema "roles" do
    field :name, :string
    field :description, :string

    timestamps()
  end

  @doc false
  def changeset(role, attrs) do
    role
    |> cast(attrs, [:name, :description])
    |> validate_required([:name, :description])
  end
end

app/lib/noodl_web/controllers/accounts_controller.ex
defmodule NoodlWeb.AccountsController do
  use NoodlWeb, :controller

  alias Phoenix.LiveView.Controller
  alias Noodl.Accounts
  alias Noodl.Accounts.User
  alias Noodl.MultiProvider
  alias NoodlWeb.Endpoint
  alias NoodlWeb.Live.Accounts, as: LiveAccounts

  @max_age 86_400

  def sign_up(conn, %{"user" => %{"agree_terms" => "false"} = user}) do
    conn
    |> put_layout("bare.html")
    |> put_flash(:info, "Must accept terms to sign up.")
    |> Controller.live_render(LiveAccounts.SignUp,
      session: %{
        "changeset" => Accounts.User.signup_changeset(%User{}, user)
      }
    )
  end

  def sign_up(conn, %{"user" => user}) do
    with {:ok, %{user: user}} <- Accounts.create_user(user) do
      conn
      |> put_flash(:info, "Account created, check your email for confirmation.")
      |> put_session(:user, user.id)
      |> redirect(to: Routes.live_path(conn, LiveAccounts.Profile))
    else
      {:error, :user, %Ecto.Changeset{} = changeset, _} ->
        conn
        |> put_flash(:error, "Invalid user")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.SignUp,
          session: %{
            "changeset" => changeset
          }
        )

      e ->
        IO.inspect(e)

        conn
        |> put_flash(:error, "Unknown Error")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.SignUp,
          session: %{
            "changeset" => Accounts.User.signup_changeset(%User{}, %{})
          }
        )
    end
  end

  def login(conn, %{"user" => user}) do
    case Accounts.login_user(user) do
      {:ok, %{confirmed: true} = user} ->
        conn
        |> put_session(:user, user.id)
        # Doing this lets us disconnect a user globally. Like if we need to permaban
        # https://hexdocs.pm/phoenix_live_view/security-model.html#disconnecting-all-instances-of-a-given-live-user
        |> put_session(:live_socket_id, "users_socket:#{user.id}")
        |> redirect(
          to: NavigationHistory.last_path(conn) || Routes.live_path(conn, Live.Pages.Index)
        )

      {:ok, user} ->
        conn
        |> put_flash(:error, "You must confirm your account before you can sign in.")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.Login,
          session: %{
            "changeset" => Accounts.User.login_changeset(user, %{}),
            "user" => user
          }
        )

      {:error, changeset} ->
        conn
        |> put_flash(:error, "Invalid login information")
        |> put_layout("bare.html")
        |> Controller.live_render(LiveAccounts.Login,
          session: %{
            "changeset" => changeset,
            "user" => user
          }
        )
    end
  end

  def logout(conn, _params) do
    conn
    |> clear_session()
    |> delete_resp_cookie("ack")
    |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
  end

  def connect(%{assigns: %{user: user}} = conn, %{"state" => state, "code" => account}) do
    # validate the incoming phoenix token
    # make sure its id is the same as the logged in person
    # update their account with the stripe account id
    with {:ok, user_id} <-
           Phoenix.Token.verify(Endpoint, "noodl stripe salt", state, max_age: @max_age),
         true <- user_id == user.id,
         {:ok, token} <- Stripe.Connect.OAuth.token(account),
         {:ok, user} <- Accounts.update_user(user, %{"stripe_account" => token.stripe_user_id}) do
      conn
      |> put_flash(:info, "Account connected.")
      |> put_session(:user, user.id)
      |> redirect(to: Routes.live_path(conn, Live.Accounts.Profile))
    else
      _ -> conn |> resp(403, "Unauthorized")
    end
  end

  def connect(conn, _params) do
    conn
    |> put_flash(:info, "Error occurred while connecting account.")
    |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
  end

  def confirmation(conn, %{"token" => token}) do
    with {:ok, user_id} <-
           Phoenix.Token.verify(Endpoint, "noodl confirmation", token, max_age: @max_age * 7),
         {:ok, user} <- Accounts.get_user(user_id),
         {:ok, user} <- Accounts.update_user(user, %{"confirmed" => true}) do
      conn
      |> put_flash(:info, "Account confirmed!")
      |> put_session(:user, user.id)
      |> redirect(to: Routes.live_path(conn, Live.Accounts.Profile))
    else
      _ -> conn |> resp(403, "Unauthorized")
    end
  end

  def unsubscribe(conn, %{"token" => token}) do
    with {:ok, %{email: email, type: type}} <-
           Phoenix.Token.verify(Endpoint, "noodl unsubscribe", token),
         {:ok, _sub} <-
           Accounts.create_subscription(%{
             "email" => email,
             "type" => type,
             "unsubscribed" => true
           }) do
      conn
      |> put_flash(:info, "You are now unsubscribed!")
      |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
    else
      {:error,
       %{
         errors: [
           email:
             {"has already been taken",
              [constraint: :unique, constraint_name: "subscriptions_email_type_index"]}
         ]
       }} ->
        conn
        |> put_flash(:info, "You have already unsubscribed.")
        |> redirect(to: Routes.live_path(conn, Live.Pages.Index))

      _ ->
        conn
        |> put_flash(:error, "An error occurred while unsubscribing. Please contact support.")
        |> redirect(to: Routes.live_path(conn, Live.Pages.Index))
    end
  end

  def oauth(conn, %{"provider" => provider} = params)
      when provider in ["github", "apple", "google"] do
    params = Map.delete(params, "provider")

    {:ok, %{user: %{"email" => email}}} = MultiProvider.callback(String.to_atom(provider), params)

    case Accounts.get_user_by(email: email) do
      {:ok, user} ->
        conn
        |> put_session(:user, user.id)
        |> put_session(:live_socket_id, "users_socket:#{user.id}")
        |> put_resp_cookie("ack", %{user_id: user.id}, sign: true)
        |> redirect(to: Routes.live_path(conn, LiveAccounts.Profile))

      {:error, :not_found} ->
        {:ok, %{user: user}} =
          Accounts.create_oauth_user(%{"email" => email, "confirmed" => true})

        conn
        |> put_session(:user, user.id)
        |> put_session(:live_socket_id, "users_socket:#{user.id}")
        |> redirect(to: Routes.live_path(conn, LiveAccounts.Profile))
    end
  end
end

app/lib/noodl_web/live/accounts/communication/communication.ex
defmodule NoodlWeb.Live.Accounts.Communication do
  @moduledoc ~S"""
  LiveView for the accounts communication page.
  """
  use NoodlWeb, :live_view

  require Logger

  alias Noodl.{Accounts, Repo}
  alias Noodl.Accounts.Subscription

  @subscription_types ["session_start", "promotional", "new_events"]

  def mount(_params, session, socket) do
    %{assigns: %{user: user}} =
      socket
      |> Authentication.assign_user(session)

    user = Repo.preload(user, [:push_subscription, :subscriptions])

    {:ok,
     socket
     |> assign(
       user: user,
       push_subscription: nil,
       subscriptions:
         Enum.reduce(@subscription_types, %{}, fn type, acc ->
           sub =
             Enum.find(user.subscriptions, &(&1.type == type)) ||
               %Subscription{type: type, user_id: user.id, email: user.email}

           Map.put(acc, type, sub)
         end)
     )}
  end

  def handle_event("unsubscribe", _, %{assigns: %{push_subscription: subscription}} = socket) do
    {:ok, _push_sub} = Accounts.delete_push_subscription(subscription)
    {:noreply, socket |> assign(push_subscription: nil)}
  end

  def handle_event(
        "update_preferences",
        %{"preferences" => preferences},
        %{assigns: %{subscriptions: subscriptions}} = socket
      ) do
    Enum.map(subscriptions, fn {type, subscription} ->
      # "false" here means that they want to be unsubscribed which is unsubscribed: true
      subscription
      |> Accounts.change_subscription()
      |> Ecto.Changeset.put_change(:unsubscribed, preferences[type] == "false")
    end)
    |> Accounts.insert_or_update_subscriptions()
    |> case do
      {:ok, subscriptions} ->
        {:noreply,
         socket
         |> put_flash(:info, "Your notifications preferences have been updated.")
         |> assign(subscriptions: subscriptions)}

      _ ->
        {:noreply, socket |> put_flash(:info, "There was a problem updating your preferences.")}
    end
  end

  def handle_event(
        "existing_subscription",
        %{
          "keys" => %{
            "auth" => public_key,
            "p256dh" => private_key
          }
        },
        socket
      ) do
    subscription =
      Accounts.get_push_subscription_by!(public_key: public_key, private_key: private_key)

    {:noreply, socket |> assign(push_subscription: subscription)}
  end

  def handle_event("error", payload, socket) do
    Logger.error(inspect(payload))

    {:noreply, socket}
  end

  def handle_event(
        "enable_subscriptions",
        %{
          "endpoint" => endpoint,
          "keys" => %{
            "auth" => auth,
            "p256dh" => pk
          }
        },
        %{assigns: %{user: user}} = socket
      ) do
    case Accounts.create_push_subscription(%{
           "user_id" => user.id,
           "endpoint" => endpoint,
           "public_key" => auth,
           "private_key" => pk
         }) do
      {:ok, push_subscription} ->
        {:noreply,
         socket
         |> assign(push_subscription: push_subscription)}

      _e ->
        {:noreply,
         socket
         |> put_flash(:info, "Could not enable push notifications.")}
    end
  end

  def is_subscribed?(subscriptions, field) do
    is_nil(subscriptions[field]) ||
      not subscriptions[field].unsubscribed
  end
end

app/lib/noodl_web/live/accounts/events/events.ex
defmodule NoodlWeb.Live.Accounts.Events do
  @moduledoc ~S"""
  LiveView for the accounts profile page.
  """
  use NoodlWeb, :live_view

  alias Noodl.{Events, Ticketing}
  alias NoodlWeb.EventsView

  def mount(_params, %{"user" => id} = session, socket) do
    events = Ticketing.get_user_future_events(id)
    current_created_events = Events.get_created_events(id)
    expired_created_events = Events.get_expired_events(id)
    %{assigns: %{user: user}} = socket = Authentication.assign_user(socket, session)

    {:ok,
     socket
     |> assign(
       user: user,
       event_tickets: events,
       current_created_events: current_created_events,
       expired_created_events: expired_created_events
     )}
  end

  def format_event_date(%{redeemed_at: redeemed_at}) do
    case Timex.format(redeemed_at, "%B %d, %Y", :strftime) do
      {:ok, time} -> time
      _ -> ""
    end
  end

  def format_event_start_time(%{start_datetime: start_datetime}, timezone) do
    start_datetime = Timex.to_datetime(start_datetime, timezone)

    case Timex.format(start_datetime, "%l %p %Z", :strftime) do
      {:ok, time} -> "#{Timex.from_now(start_datetime)} at #{time}"
      _ -> ""
    end
  end

  def format_time(time, str) do
    case Timex.format(time, str, :strftime) do
      {:ok, time} -> time
      _ -> ""
    end
  end

  def event_role(_user_id, _) do
    "Creator"
  end

  defdelegate cover_photo_url(event), to: EventsView
  defdelegate user_timezone(socket), to: EventsView
end

app/lib/noodl_web/live/accounts/forgot_password/forgot_password.ex
defmodule NoodlWeb.Live.Accounts.ForgotPassword do
  @moduledoc ~S"""
  LiveView for the forgot password page.
  """
  use NoodlWeb, :bare_view

  alias Noodl.Accounts
  alias Noodl.Accounts.User
  alias Noodl.Emails.Mailer
  alias NoodlWeb.Email

  @timeout :timer.seconds(5)

  def mount(_params, _session, socket) do
    {:ok,
     assign(socket,
       changeset: Accounts.User.forgot_password_changeset(%User{}, %{}),
       validating: false,
       reset_locked: false,
       message: ""
     )}
  end

  def handle_event("validate", %{"user" => user}, socket) do
    {:noreply, assign(socket, changeset: User.login_changeset(%User{}, user), validating: true)}
  end

  def handle_event(
        "submit",
        %{"user" => %{"email" => email}},
        %{assigns: %{reset_locked: false}} = socket
      ) do
    # If someone resets password, don't let them fire it again for another 3 seconds
    # so they can't spam emails or tokens to figure out our secret
    Process.send_after(self(), :reset_available, @timeout)

    case Accounts.get_user_by(email: email) do
      {:ok, user} ->
        message = user |> Email.forgot_password()
        Mailer.send_now(user.email, "account", message)

      _ ->
        false
    end

    {:noreply,
     socket |> put_flash(:info, "Password reset email sent.") |> assign(reset_locked: true)}
  end

  def handle_event("submit", _, socket),
    do: {:noreply, socket |> put_flash(:info, "Wait a few seconds to try again.")}

  def handle_info(:reset_available, socket) do
    {:noreply, socket |> clear_flash(:info) |> assign(reset_locked: false)}
  end
end

app/lib/noodl_web/live/accounts/profile/profile.html.leex
<div class="min-h-screen pt-16 pb-12 bg-gray-100">
  <div class="px-4 mx-auto max-w-7xl sm:px-6 lg:px-8 lg:flex md:justify-between">
    <%= Phoenix.View.render NoodlWeb.AccountsView, "sidebar.html", Map.put(assigns, :view, "profile") %>

    <div class="flex-1 mt-8 md:mt-0">
      <div class="rounded-md shadow">
        <div class="bg-white">
          <header class="px-4 pt-5 sm:pt-6 sm:px-6">
            <h1 class="text-lg font-medium leading-6 text-gray-900">
              Profile
            </h1>
            <p class="mt-1 text-sm leading-5 text-gray-500">
              Tell us a little about yourself.
            </p>
          </header>

          <%= if is_nil(@user.stripe_account) do %>
            <div class="px-4 mt-6 sm:px-6">
              <span class="text-sm font-medium leading-5 text-gray-700">
                Stripe Integration
              </span>
              <a class="block mt-1" aria-label="Connect to Stripe" href="<%= stripe_connect_url(@state, @user.email) %>">
                <img class="w-48" src="<%= Routes.static_path(@socket, "/images/stripe/light-on-light.png") %>" />
              </a>

              <span class="block mt-2 text-xs text-gray-500">Your Stripe information will not be public.</span>
            </div>
          <% end %>

          <%= form_for @changeset, "#", [phx_submit: :submit, phx_change: :validate, multipart: true, class: "mt-6", autocomplete: "off", phx_ignore: "update"], fn f -> %>
            <div class="px-4 sm:px-6">
              <div class="block w-full sm:flex">
                <%= label f, :firstname, class: "block w-full sm:w-1/2 lg:w-1/3" do %>
                  <span class="text-sm font-medium leading-5 text-gray-700">First name</span>
                  <%= text_input f, :firstname, [placeholder: "Jane", class: "mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none transition duration-150 ease-in-out sm:text-sm sm:leading-5"] %>
                  <%= if @validating and not is_nil(@changeset.errors[:firstname]) do %>
                    <%= error_tag @changeset, :firstname, [class: "block mt-2 text-sm text-red-600"] %>
                  <% end %>
                <% end %>

                <%= label f, :lastname, class: "block w-full sm:w-1/2 lg:w-1/3 mt-6 sm:mt-0 sm:ml-4" do %>
                  <span class="text-sm font-medium leading-5 text-gray-700">Last name</span>
                  <%= text_input f, :lastname, [placeholder: "Doe", class: "mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none transition duration-150 ease-in-out sm:text-sm sm:leading-5"] %>
                  <%= if @validating and not is_nil(@changeset.errors[:lastname]) do %>
                    <%= error_tag @changeset, :lastname, [class: "block mt-2 text-sm text-red-600"] %>
                  <% end %>
                <% end %>
              </div>

              <div class="mt-6">
                <%= label f, :display_name, class: "block w-full md:w-1/2" do %>
                  <span class="text-sm font-medium leading-5 text-gray-700">Display Name</span>
                  <%= text_input f, :display_name, [class: "mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none transition duration-150 ease-in-out sm:text-sm sm:leading-5"] %>
                  <span class="block mt-1 text-xs text-gray-500">Choose a name to appear in chat.</span>
                  <%= if @validating and not is_nil(@changeset.errors[:display_name]) do %>
                    <%= error_tag @changeset, :display_name, [class: "block mt-2 text-sm text-red-600"] %>
                  <% end %>
                <% end %>
              </div>

              <div class="mt-6 block w-full sm:flex">
                <%= label f, :social_username, class: "block w-full sm:w-1/2 lg:w-1/3" do %>
                  <span class="text-sm font-medium leading-5 text-gray-700">Social Handle</span>
                  <%= text_input f, :social_username, [placeholder: "@twitter_handle", class: "mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none transition duration-150 ease-in-out sm:text-sm sm:leading-5"] %>
                  <%= if @validating and not is_nil(@changeset.errors[:social_username]) do %>
                    <%= error_tag @changeset, :social_username, [class: "block mt-2 text-sm text-red-600"] %>
                  <% end %>
                <% end %>

                <%= label f, :social_link, class: "block w-full sm:w-1/2 lg:w-1/3 mt-6 sm:mt-0 sm:ml-4" do %>
                  <span class="text-sm font-medium leading-5 text-gray-700">Social URL</span>
                  <%= text_input f, :social_link, [placeholder: "https://twitter.com/Twitter", class: "mt-1 form-input block w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none transition duration-150 ease-in-out sm:text-sm sm:leading-5"] %>
                  <%= if @validating and not is_nil(@changeset.errors[:social_link]) do %>
                    <%= error_tag @changeset, :social_link, [class: "block mt-2 text-sm text-red-600"] %>
                  <% end %>
                <% end %>
              </div>

              <div class="mt-6">
                <div class="sm:col-span-6">
                  <label for="photo" class="block text-sm font-medium text-gray-700">
                    Profile Photo
                  </label>
                  <div class="mt-2 flex items-center">
                    <%= if not Enum.empty?(@uploads.profile_photo.entries) do %>
                      <%= for entry <- @uploads.profile_photo.entries do %>
                        <span class="h-12 w-12 rounded-full overflow-hidden bg-gray-100"
                              phx-click="remove_image"
                              phx-value-ref="<%= entry.ref %>"
                        >
                          <%= live_img_preview entry, alt: "Profile Photo Thumbnail", class: "object-cover w-12 h-12 max-w-full overflow-hidden bg-gray-100 rounded-full profile-photo-thumbnail"%>
                        </span>
                      <% end %>
                    <% else %>
                      <span class="h-12 w-12 rounded-full overflow-hidden bg-gray-100">
                        <img alt="Profile photo thumbnail" class="object-cover w-12 h-12 max-w-full overflow-hidden bg-gray-100 rounded-full" src="<%= profile_photo_url(@user) %>" />
                      </span>
                    <% end %>

                    <button type="button"
                            phx-hook="Upload"
                            id="profile-upload"
                            class="ml-5 bg-white py-2 px-3 border border-gray-300 rounded-md shadow-sm text-sm leading-4 font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500">
                      Change
                    </button>
                    <%= live_file_input @uploads.profile_photo, class: "sr-only" %>
                  </div>
                </div>
              </div>

              <div class="mt-6" phx-update="ignore">
                <%= error_tag @changeset, :profile_photo, [class: "block mt-2 text-sm text-red-600"] %>
              </div>
            </div>

            <div class="px-4 py-3 text-right bg-gray-50 sm:px-6">
              <span class="inline-flex rounded-md shadow-sm">
                <button type="submit" class="<%= UI.button(:primary, :sm) %>" phx-disable-with="Updating...">
                  Update
                </button>
              </span>
            </div>
          <% end %>
        </div>
      </div>

      <div class="rounded-md bg-white shadow mt-8 px-4 py-5">
        <h1 class="py-2 text-lg font-medium leading-6 text-gray-900">
          Delete account
        </h1>

        <p class="py-2 text-sm font-medium leading-5 text-gray-700">
          Click below to delete your account and all associated data. <span class="uppercase text-blue-600">This cannot be undone.</span>
        </p>

        <form action="#" phx-submit="delete_account">
          <button data-confirm="Are you sure?" type="submit" class="<%= UI.button(:primary, :sm) %>" phx-disable-with="Updating...">
            Delete Account
          </button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="hidden">
  <div class="fixed inset-x-0 bottom-0 px-4 pb-6 sm:inset-0 sm:p-0 sm:flex sm:items-center sm:justify-center">
    <div tabindex="-1" class="fixed inset-0 transition-opacity">
      <div class="absolute inset-0 bg-gray-500 opacity-75"></div>
    </div>

    <div
      id="modal"
      class="px-4 pt-5 pb-4 overflow-y-scroll transition-all transform bg-white rounded-lg shadow-xl sm:max-w-lg sm:w-full sm:p-6"
      role="dialog"
      aria-modal="true"
      aria-labelledby="modal-headline"
    >
      <div>
        <h2 class="text-lg font-medium leading-6 text-gray-900" id="modal-headline">
          Upload Profile Photo
        </h2>
        <div class="mt-4">
          <div class="h-80">
            <img data-modal-image class="block w-full h-full max-w-full" src="https://via.placeholder.com/150">
          </div>

          <div class="mt-5 sm:mt-6 sm:grid sm:grid-cols-2 sm:gap-3 sm:grid-flow-row-dense">
            <span class="flex w-full rounded-md shadow-sm sm:col-start-2">
              <button data-crop-button class="inline-flex justify-center w-full px-4 py-2 text-base font-medium leading-6 text-white transition duration-150 ease-in-out bg-red-500 border border-transparent rounded-md shadow-sm hover:bg-red-400 focus:outline-none focus:border-red-700 focus:shadow-outline-red sm:text-sm sm:leading-5">
                Submit
              </button>
            </span>
            <span class="flex w-full mt-3 rounded-md shadow-sm sm:mt-0 sm:col-start-1">
              <button type="button" data-modal-close class="inline-flex justify-center w-full px-4 py-2 text-base font-medium leading-6 text-gray-700 transition duration-150 ease-in-out bg-white border border-gray-300 rounded-md shadow-sm hover:text-gray-500 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue sm:text-sm sm:leading-5">
                Cancel
              </button>
            </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%= Phoenix.View.render NoodlWeb.LayoutView, "_footer.html", assigns %>